# fundintel/universe.py
# Combine ORIGINAL + CUSTOM lists, remove duplicates, preserve order

# ---- ORIGINAL (exact, unchanged)
ORIGINAL_UNIVERSE = [
    # ---- Core US equity (large/mid/small; multi-issuer)
    "SPY","IVV","VOO","SPLG","VTI","SCHB","ITOT","IWB","IWM","IJH","IJR","VO","VB",
    # ---- Equal-weight & alt core
    "RSP","QQQ","QQQM","DIA","VUG","VTV","IWF","IWD","MGK","VBR","VOT","AVUS",
    # ---- Sectors (SPDR + alternates)
    "XLK","XLF","XLE","XLY","XLP","XLV","XLI","XLU","XLRE","XLC","XLB",
    "VDE","VHT","VCR","VDC","VIS","VAW","VPU","VNQ","VOX",
    # ---- Factor / dividend / low vol
    "SCHD","VYM","DVY","HDV","NOBL","QUAL","MTUM","USMV","SPLV","SPHB","VLUE",
    # ---- International developed & EM (broad + region + country)
    "VEA","VXUS","IXUS","EFA","IEFA","EEM","IEMG","VWO","SCZ","EWC","EWA","EWJ",
    "EWG","EWU","EWL","EWQ","EWP","EWT","EWY","EWH","INDA","EWZ","ARGT","EZA",
    # ---- Real estate
    "VNQ","IYR","SCHH","XLRE",
    # ---- Commodities / gold & silver
    "GLD","IAU","SGOL","SLV","DBC","PDBC","GSG",
    # ---- Bonds / rates / credit / cash-like
    "AGG","BND","SCHZ","IUSB","LQD","VCIT","HYG","JNK",
    "SHY","IEF","IEI","TLT","ZROZ","VTIP","TIP","STIP",
    "SGOV","BIL","SHV",
    # ---- Thematics & semis/biotech/clean energy/uranium
    "ARKK","ARKW","SOXX","SMH","XBI","IBB","TAN","ICLN","URA","CIBR","BOTZ",
    # ---- Leveraged & inverse (penalized by Structure)
    "TQQQ","SQQQ","UPRO","SPXU","SOXL","SOXS","FNGU","FNGD",
    # ---- Popular mutual funds (Vanguard/Fidelity/Schwab)
    "VTSAX","VFIAX","VBTLX","VWNAX","VEMAX","FXAIX","FSKAX","SWPPX","SWISX","SWTSX",
    # ---- Closed-end funds (sample)
    "PDI","PDO","UTF","UTG","BST",
    # ---- Others
    "^GSPC", "USD"
]

# ---- MY CUSTOM LIST (exact text you provided; kept as a single string for easy maintenance)
CUSTOM_UNIVERSE_RAW = """
SPY,IVV,VOO,SPLG,VTI,SCHB,ITOT,IWB,IWM,IJH,IJR,VO,VB,RSP,QQQ,QQQM,DIA,VUG,VTV,IWF,IWD,MGK,VBR,VOT,AVUS,XLK,XLV,XLF,XLE,XLY,XLP,XLU,XLRE,XLC,XLB,VDE,VHT,VCR,VDC,VIS,VAW,VPU,VNQ,VOX,SCHD,DVY,HDV,NOBL,QUAL,MTUM,USMV,SPLV,SPHB,VLUE,VEA,VXUS,IXUS,EFA,IEFA,EEM,IEMG,VWO,SCZ,EWC,EWA,EWJ,EWG,EWQ,EWL,EWU,EWD,EWP,EWN,EWI,INDA,EWZ,ARGT,EZA,VNQI,IYR,SCHH,XLRE,GLD,IAU,SGOL,SLV,DBP,PDBC,GSG,AGG,BND,SCHZ,IUSB,LQD,VCIT,HYG,JNK,SHY,IEF,IEI,TLT,ZROZ,VTIP,TIP,STIP,SGOV,BIL,SHV,ARKK,ARKW,SOXX,SMH,XBI,IBB,TAN,ICLN,URA,CIBR,BOTZ,TQQQ,SQQQ,UPRO,SPXU,SOXL,SOXS,FNGU,VTSAX,VFIAX,VBTLX,VWNAX,VEMAX,FXAIX,FSKAX,SWPPX,SWISX,SWTXX,PDI,UTG,BST,^GSPC,USD,

TECL,TECS,LABU,LABD,SPXL,SPXS,UVXY,VIXY,NUGT,DUST,JDST,JNUG,SOXL,SOXS,WEBL,WEBS,CURE,DRN,DRV,ERX,ERY,TAN,ICLN,PAVE,XOP,USO,UNG,DBO,KOLD,BOIL,DBC,DBA,CORN,WEAT,SOYB,URA,LIT,BATT,HACK,CIBR,CLOU,FINX,ARKF,ARKG,ARKQ,ARKX,PRNT,GAMR,HERO,IBUY,FDN,SKYY,FTEC,VGT,IYW,IYZ,FUTY,XTL,XHB,ITB,REM,KBWB,KRE,IAT,XRT,FDIS,PEJ,PSJ,PJUN,PJAN,PSL,PSCC,PSCH,PSCM,PSCE,PSCD,PSCF,PSCI,PSCT,PSCU,PBJ,PSCF,VOOG,VOOV,VONG,VONV,VTHR,VBK,VBR,VTWV,VTWG,MGV,MGC,SLYG,SLYV,IJS,IJJ,IJK,MDY,MDYG,MDYV,SPMD,SPYG,SPYV,RWJ,RWL,SPHQ,COWZ,NOBL,SDY,VIG,DIVY,DIV,PEY,SPYD,HDV,DLN,FVD,DVY,DTD,LVHD,USMV,SPLV,EFAV,ACWV,EEMV,IGRO,SCHD,VYM,VYMI,VIGI,DGS,DEM,EELV,SCHE,FLQG,FLQE,FLQD,FLQL,FLQS,FLGR,FLRG,

FSAGX,FSELX,FBMPX,ALGRX,JAGTX,FCNTX,FMAGX,FZROX,FZILX,FZIPX,FDGRX,FSCSX,FSPTX,FSRFX,FSLGX,FBCVX,FMIEX,FOCPX,FFIDX,FEQIX,FEMKX,FSCRX,FSHCX,FBSOX,FSPHX,FSELX,FLCSX,FSMEX,FPURX,FCNTX,FGRTX,FDCAX,FLGEX,FSTFX,FJPNX,FSUVX,FHLSX,FRESX,FCVSX,FSAVX,FSLVX,FSPGX,FSLEX,FDRR,FVAL,FDMO,FDLO,FQAL,FIDI,FDVV,FREL,FSTA,FTEC,FUTY,FENY,FMAT,FDIS,FCOM,FDHY,FBND,FXNAX,FTHRX,FCOR,FSIGX,FJRLX,FNTNX,FXNCX,FXNAX,FZROX,FZILX,FZLTX,FZIPX
""".strip()

# ---- Build DEFAULT_UNIVERSE by merging & de-duplicating (preserve order)
def _parse_csv_block(s: str):
    out = []
    for raw in s.split(","):
        t = raw.strip()
        if t:
            out.append(t)
    return out

CUSTOM_UNIVERSE = _parse_csv_block(CUSTOM_UNIVERSE_RAW)

# Use dict.fromkeys to keep first occurrence and drop duplicates while preserving order.
DEFAULT_UNIVERSE = list(dict.fromkeys(ORIGINAL_UNIVERSE + CUSTOM_UNIVERSE))
